//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banksystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Konto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Konto()
        {
            this.Transaktion = new HashSet<Transaktion>();
        }
    
        public int KontoID { get; set; }
        public int UserID { get; set; }
        public decimal Kontostand { get; set; }
    
        public virtual Konto Konto1 { get; set; }
        public virtual Konto Konto2 { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaktion> Transaktion { get; set; }
    }
}
