//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banksystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int LoginID { get; set; }
        public string Username { get; set; }
        public byte isAdmin { get; set; }
        public int UserID { get; set; }
        public string Password_Hash { get; set; }
        public string Salt { get; set; }
    
        public virtual Login Login1 { get; set; }
        public virtual Login Login2 { get; set; }
        public virtual Users Users { get; set; }
    }
}
