//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banksystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaktion
    {
        public int TransaktionID { get; set; }
        public decimal Amount { get; set; }
        public string Comment { get; set; }
        public System.DateTime Date { get; set; }
        public int KontoID { get; set; }
    
        public virtual Konto Konto { get; set; }
        public virtual Transaktion Transaktion1 { get; set; }
        public virtual Transaktion Transaktion2 { get; set; }
    }
}
